### PR TITLE
feat: Add 'children' property

### PR DESCRIPTION
**Pull request by tangposmarvin**
This fixes for this Property 'children' does not exist on type ...
lint

### CODE REVIEW

**Comment by scttcper** [comment]
Are there any docs on backup working that way?

**Comment by tangposmarvin** [comment]
@scttcper we get this from here https://support.google.com/adsense/answer/10762946?hl=en 
Screenshot from 2022-05-19 07-02-55

**Comment by scttcper** [comment]
Thanks for the link

**Pull request merged**
